///////////////////////////////////////////////////////////
//  CheckErrorType.cs
//  Implementation of the Enumeration CheckErrorType
//  Generated by Enterprise Architect
//  Created on:      20-4ÔÂ-2018 10:39:01
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum CheckErrorType : int {

    ExcelRead,
    ExcelStructure,
	TemplateMatch,
	PKCheck,
	FKCheck,
	ColumnCheck

}//end CheckErrorType