///////////////////////////////////////////////////////////
//  ColumnRule.cs
//  Implementation of the Class ColumnRule
//  Generated by Enterprise Architect
//  Created on:      19-4月-2018 17:36:44
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Rules {
	public class ColumnRule {
		public string ColumnName{ get;  set;} 
		public int ColumnIndex{ get;  set;} 
		public string ExampleData{ get;  set;} 
		public string Remark{ get;  set;} 
		/// <summary>
		/// 实际数据类型
		/// </summary>
		public string MeanDataType{ get;  set;} 
		/// <summary>
		/// 数据库数据类型
		/// </summary>
		public string DbDataType{ get;  set;} 
		public int FieldLength{ get;  set;} 
		public bool IsNullable{ get;  set;} 
		public bool IsPk{ get;  set;} 
		public bool IsFk{ get;  set;} 
		public string FKColumnName{ get;  set;} 
		public Dictionary<string,decimal> DictList{ get;  set;} 
		public int FieldSacle{ get;  set;} 
		public decimal? DecimalMax{ get;  set;} 
		public decimal? DecimalMin{ get;  set;} 
		public DateTime? DateTimeMin{ get;  set;} 
		public DateTime? DateTimeMax{ get;  set;} 

        
    }//end ColumnRule

}//end namespace Rules