///////////////////////////////////////////////////////////
//  ExcelCheckError.cs
//  Implementation of the Class ExcelCheckError
//  Generated by Enterprise Architect
//  Created on:      19-4ÔÂ-2018 12:56:51
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ExcelCheckError {
	 
	public string FileName{ get;  set;} 	
	public string ErrorType{ get;  set;} 
	public string ErrorBrief{ get;  set;} 
	public string ErrorDetail{ get;  set;} 
	public Dictionary<string,List<string>> ErrorList{ get;  set;} 


    public ExcelCheckError(string errorType)
    {        
        this.ErrorType = errorType;
        this.ErrorList = new Dictionary<string, List<string>>();
    }

    public ExcelCheckError(string errorType, Dictionary<string, List<string>> errorList) : this(errorType)
    {
        this.ErrorList = ErrorList;
    }

    public void AppendError(string key, string message)
    {
        if (!ErrorList.ContainsKey(key))
        {
            this.ErrorList.Add(key, new List<string>());
        }
        this.ErrorList[key].Add(message);
    }

}//end ExcelCheckError