///////////////////////////////////////////////////////////
//  ExcelColumn.cs
//  Implementation of the Class ExcelColumn
//  Generated by Enterprise Architect
//  Created on:      18-4ÔÂ-2018 10:00:56
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Excels {
	public class ExcelColumn {

		public int ColumnIndex{ get;  set;} 
		public string ColumnName{ get;  set;} 

		public ExcelColumn(){

		}

	}//end ExcelColumn

}//end namespace Excels