///////////////////////////////////////////////////////////
//  ExcelSheet.cs
//  Implementation of the Class ExcelSheet
//  Generated by Enterprise Architect
//  Created on:      18-4ÔÂ-2018 10:00:14
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



namespace Excels {
	public class ExcelSheet {

		public int SheetIndex{ get;  set;} 
		public string SheetName{ get;  set;} 
		public IList<ExcelColumn> Columns{ get;  set;} 

		public ExcelSheet(){
            Columns = new List<ExcelColumn>();
		}       

        public int ColumnNum
        {
            get
            {
                return Columns?.Count() ?? 0;
            }
        }

        public ExcelColumn this[int index]
        {
            get
            {
                return Columns?[index];
            }
        }

        public ExcelColumn this[string name]
        {
            get
            {
                return Columns?.FirstOrDefault(f => name.Equals(f.ColumnName));
            }
        }

    }//end ExcelSheet

}//end namespace Excels