///////////////////////////////////////////////////////////
//  ExcelCheckReport.cs
//  Implementation of the Class ExcelCheckReport
//  Generated by Enterprise Architect
//  Created on:      20-4ÔÂ-2018 10:39:05
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ExcelCheckReport {

	public Dictionary<CheckErrorType,ExcelCheckError> CheckErrorList{ get;  set;}

    public ExcelCheckReport()
    {
        this.CheckErrorList = new Dictionary<CheckErrorType, ExcelCheckError>();
    }

   
    public void ExcelReadError(string key, string message)
    {
        Error(CheckErrorType.ExcelRead, key, message);
    }

    public void ExcelStructureError(string key,string message)
    {
        Error(CheckErrorType.ExcelStructure, key, message);
    }

    public void TemplateMatchError(string key, string message)
    {
        Error(CheckErrorType.TemplateMatch, key, message);
    }

    public void PkError(string key, string message)
    {
        Error(CheckErrorType.PKCheck, key, message);
    }

    public void FkError(string key, string message)
    {
        Error(CheckErrorType.FKCheck, key, message);
    }

    public void ColumnError(string key, string message)
    {
        Error(CheckErrorType.ColumnCheck, key, message);
    }
   

    private void Error(CheckErrorType type, string key, string message)
    {
        if (!CheckErrorList.ContainsKey(type))
            CheckErrorList.Add(type, new ExcelCheckError(key));
        CheckErrorList[type].AppendError(key, message);
    }

    public void Clear(CheckErrorType type)
    {
        if (CheckErrorList.ContainsKey(type))
            CheckErrorList[type].ErrorList.Clear();
    }

}//end ExcelCheckReport