///////////////////////////////////////////////////////////
//  ExcelModel.cs
//  Implementation of the Class ExcelModel
//  Generated by Enterprise Architect
//  Created on:      18-4ÔÂ-2018 9:35:47
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



namespace Excels {
	public class ExcelStructure
    {        
        public string Name{ get;  set;} 
		public IList<ExcelSheet> Sheets{ get;  set;} 

		public ExcelStructure(){
            Sheets = new List<ExcelSheet>();
		}

        public bool Contains(string sheetName)
        {
            return Sheets?.Any(s => s.SheetName == sheetName) ?? false;
        }

        public int SheetNum{
            get
            {
                return Sheets?.Count() ?? 0;
            }
		}

        public ExcelSheet this[int index]
        {
            get
            {
                return Sheets?[index];
            }
        }

        public ExcelSheet this[string name]
        {
            get
            {
                return Sheets?.FirstOrDefault(f => name.Equals(f.SheetName));
            }
        }

	}//end ExcelModel

}//end namespace Excels