///////////////////////////////////////////////////////////
//  ITinyReader.cs
//  Implementation of the Interface ITinyReader
//  Generated by Enterprise Architect
//  Created on:      06-5ÔÂ-2018 12:16:56
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.TinyEtl
{
    public interface ITinyReader
    {
        event EventHandler<TinyBeginLoadEventArgs> BeginLoad;
        event EventHandler<TinyEndLoadEventArgs> EndLoad;
    }//end ITinyReader

  

   

}//end namespace TinyEtl