///////////////////////////////////////////////////////////
//  TemplateRule.cs
//  Implementation of the Class TemplateRule
//  Generated by Enterprise Architect
//  Created on:      18-4ÔÂ-2018 15:36:14
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;


using Rules;
namespace Rules {
	public class TemplateRule {

		public string TemplateName{ get;  set;} 
		public IList<SheetRule> SheetRules{ get;  set;} 

		public TemplateRule(){
            this.SheetRules = new List<SheetRule>();
		}        

        public int SheetNum
        {
            get
            {
                return SheetRules?.Count() ?? 0;
            }
        }

        public SheetRule this[string sheetName]
        {
            get
            {
                return SheetRules?.FirstOrDefault(f => sheetName.Equals(f.SheetName));
            }
        }
	 

	}//end TemplateRule

}//end namespace Rules