///////////////////////////////////////////////////////////
//  TinyExtensions.cs
//  Implementation of the Class TinyExtensions
//  Generated by Enterprise Architect
//  Created on:      06-5ÔÂ-2018 18:59:52
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;

namespace FD.TinyEtl {
	public static class TinyExtensions {
        public static bool IsNullOrEmpty(this string text)
        {
            return string.IsNullOrEmpty(text);
        }

        public static bool IsNull(this string text)
        {
            return text == null;
        }

    

        public static bool IsNullOrWhiteSpace(this string text)
        {
            return string.IsNullOrWhiteSpace(text);
        }
    }//end TinyExtensions

}//end namespace FD.TinyEtl