///////////////////////////////////////////////////////////
//  TinyUtility.cs
//  Implementation of the Class TinyUtility
//  Generated by Enterprise Architect
//  Created on:      06-5ÔÂ-2018 19:48:11
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.TinyEtl {
	public static class TinyUtility {

        public static void Write(this FileStream sr, string value, Encoding encoding = null)
        {
            TinyGuard.ArgumentNotNull(sr, "FileStream");

            if (value.IsNullOrEmpty())
                return;

            if (encoding == null)
                encoding = Encoding.ASCII;

            byte[] byteData = null;
            byteData = encoding.GetBytes(value);
            sr.Write(byteData, 0, byteData.Length);
        }
    }//end TinyUtility

}//end namespace FD.TinyEtl